[package]
name = "z3-bench"
version = "0.1.0"
edition = "2021"

[dependencies]
interprocess = "1.1.1"
fork = "0.1.20"
tempfile = "3.3.0"

utf8-read = "0.4.0"

num-traits = "0.2.15"
num-bigint = "0.4.3"
